language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t diablo1031/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true diablo1031/react-test npm test

after_success:
  - docker build -t diablo1031/multi-client ./client
  - docker build -t diablo1031/multi-nginx ./nginx
  - docker build -t diablo1031/multi-server ./server
  - docker build -t diablo1031/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# deploy:
#   edge: true
#   provider: elasticbeanstalk
#   region: "ap-northeast-2"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-ap-northeast-2-592379323855"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY

